name: 'Application Token Generator'
description: 'Generates an application token.'
inputs:

  github-repository:
    description: 'Repository with the application installation.'
    default: ${{ github.repository }}

  github-token:
    description: 'Token with metadata read access to the repository.'
    default: ${{ github.token }}

  app-pk:
    description: 'Application private key.'
    required: true

  app-id:
    description: 'Application identifier.'
    required: true

  duration:
    description: 'Tokens duration, defaults to 5 minutes.'
    required: false

  permissions:
    description: 'Permissions if you would like to scope them down.'
    required: false

outputs:
  token:
    description: 'Generated token.'

runs:
  using: docker
  image: docker://ghcr.io/dev-bio/actions-token@sha256:f1358394e1a5dec61d9b4f05ec2927693ba4d06c095aedce1dbc5257a4cd4524
